# Version of Docker compose file
version: "3.1"

services:
  testfiber:
    image: "test-fiber:latest"
    ports:
      - '2499:3000'
    environment:
      # ENVIRONMET_VARIABLE_NAME: "environment variable value" 
      APP_ENV: "prod"
      APP_PORT: "3000"
      APP_DB_HOST: "localhost:3002"
      APP_DB_USERNAME: "xxx"
      APP_DB_PASSWORD: "xxx"
      APP_DB_NAME: "collection_name"