# Version of Docker compose file
version: "3.1"

services:
  testfiber:
    image: "test-fiber:latest"
    ports:
      - '2499:3000'
    environment:
      # ENVIRONMET_VARIABLE_NAME: "environment variable value" 
      APP_ENV: "prod"
      APP_PORT: "3000"
      APP_DB_HOST: "203.151.199.181:27017"
      APP_DB_USERNAME: "admin"
      APP_DB_PASSWORD: "admin%40inet!"
      APP_DB_NAME: "julladith_test"